# Generated by Django 4.0.2 on 2022-03-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='药品名称')),
                ('price', models.FloatField(default=150, verbose_name='药品单价')),
                ('datetime', models.DateTimeField(max_length=19, verbose_name='入库时间')),
                ('exp', models.IntegerField(default=3, verbose_name='保质期')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
            },
        ),
    ]
