# Generated by Django 4.0.2 on 2022-03-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='药品单价'),
        ),
    ]
