# Generated by Django 4.0.2 on 2022-03-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('id',), 'verbose_name': '药品', 'verbose_name_plural': '药品'},
        ),
    ]
