# Generated by Django 4.0.2 on 2022-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_alter_storage_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='sum',
            field=models.IntegerField(default=100, verbose_name='库存'),
        ),
    ]
