# Generated by Django 4.0.2 on 2022-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='num',
            field=models.CharField(default='', max_length=256, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=256, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='', max_length=256, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.CharField(default=None, max_length=256, verbose_name='年龄'),
        ),
    ]
