# Generated by Django 4.0.2 on 2022-04-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_num_doctor_password_doctor_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='宠物名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.customer', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '宠物信息',
                'verbose_name_plural': '宠物信息',
            },
        ),
    ]
