# Generated by Django 4.0.2 on 2022-04-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息', 'verbose_name_plural': '客户信息'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': '医生信息', 'verbose_name_plural': '医生信息'},
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=256, verbose_name='主治医生')),
                ('time', models.DateTimeField(max_length=19, verbose_name='挂号时间')),
                ('price', models.FloatField(default=0.0, verbose_name='价钱')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.customer', verbose_name='用户')),
            ],
            options={
                'verbose_name': '挂号信息',
                'verbose_name_plural': '挂号信息',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(max_length=19, verbose_name='时间')),
                ('content', models.CharField(max_length=256, verbose_name='内容')),
                ('doctor', models.CharField(max_length=256, verbose_name='主治医师')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.customer', verbose_name='用户')),
            ],
            options={
                'verbose_name': '处方信息',
                'verbose_name_plural': '处方信息',
            },
        ),
    ]
