# Generated by Django 4.0.2 on 2022-04-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_customer_options_alter_doctor_options_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(max_length=19, verbose_name='时间')),
                ('exp', models.DateTimeField(max_length=19, verbose_name='过期时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.customer', verbose_name='用户')),
            ],
            options={
                'verbose_name': '预约信息',
                'verbose_name_plural': '预约信息',
            },
        ),
    ]
